Fix for safetensors >=0.8.0 (#4094)
### Changes

Convert numpy scalars to array befor save by safetensors
Functional behavior after loading remains identical.

### Reason for changes

Safetensors >= 0.8.0 requires np.array(scalar) instead of raw NumPy
scalars.


https://github.com/openvinotoolkit/nncf/actions/runs/27194077393/job/80281175625
```
FAILED tests/openvino/native/quantization/test_weights_compression_statistics_caching.py::test_weight_compression_statistics_caching - AttributeError: 'numpy.float32' object has no attribute 'ctypes'. Did you mean: 'dtype'?
```

### Related tickets

CVS-188352

### Tests


[Test
examples](https://github.com/openvinotoolkit/nncf/actions/runs/27334546713)
- success